version: '2'
services:
  web:
    build: .
    ports:
    - "80:3000"
    # env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      NODE_ENV: production
      PORT: 3000
      APP_PORT: 3000
